[package]
name = "rust-lua"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A Lua interpreter implemented in Rust"

[dependencies]
nom = "8.0.0"
thiserror = "1.0.50"

[dev-dependencies]
# テスト用の依存関係
