[package]
name = "rua"
version = "0.1.0"
edition = "2021"
authors = ["tkcd <goriponikeike55@gmail.com>"]
description = "A Lua interpreter implemented in Rust"

[dependencies]
nom = "7"
thiserror = "1.0.50"
